server.port=8082

# Database
spring.datasource.url=jdbc:postgresql://${DB_HOST:prod-db-host}:${DB_PORT:5432}/task_db
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# Logging
logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=OFF
logging.level.org.guidewire.login=INFO

logging.file.name=/var/log/task-service/task-service.log
logging.logback.rollingpolicy.file-name-pattern=/var/log/task-service/application-%d{yyyy-MM-dd}.log
logging.logback.rollingpolicy.max-history=30

# Kafka
spring.kafka.bootstrap-servers=${KAFKA_BROKERS}
