server.port=8082

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/task_db
spring.datasource.username=postgres
spring.datasource.password=password

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.javax.persistence.schema-generation.scripts.create=create
spring.jpa.properties.javax.persistence.schema-generation.scripts.create-target=target/schema-ddl.sql
spring.jpa.properties.javax.persistence.schema-generation.scripts.drop-target=target/schema-drop-ddl.sql

# Logging
logging.level.org.springframework=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.guidewire.login=TRACE

logging.file.name=logs/task-service.log

# Kafka
spring.kafka.bootstrap-servers=192.168.1.2:9092
