spring.application.name=TaskService
server.port=8082
# sql related
spring.datasource.url=jdbc:postgresql://localhost:5432/task_db
spring.datasource.username=postgres
spring.datasource.password=password
#  <create | create-drop | update | validate | none>
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.springframework=debug
# Enable Hibernate SQL logging
logging.level.org.hibernate.SQL=DEBUG
# Enable general Hibernate debug logging
# Generate DDL to an output file
spring.jpa.properties.javax.persistence.schema-generation.scripts.create=create
spring.jpa.properties.javax.persistence.schema-generation.scripts.create-target=target/schema-ddl.sql
# Optionally, add drop DDL as well
spring.jpa.properties.javax.persistence.schema-generation.scripts.drop-target=target/schema-drop-ddl.sql
# Log query parameters
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
# Log everything from TRACE to ERROR
logging.level.org.guidewire.login=TRACE
# Log file location
logging.file.name=logs/task-service.log
# Logging patterns for console and file
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
# Logback Rolling Policy Configuration
logging.logback.rollingpolicy.file-name-pattern=logs/application-%d{yyyy-MM-dd}.log  # Daily rolling logs
logging.logback.rollingpolicy.max-history=30
# Keep logs for 30 days
# External Logback configuration file
logging.config=classpath:logback-spring.xml
# Local storage paths
file.storage.local.path=/Users/cyadav/JavaProjects/TaskManager/uploads
attachments.storage.local-path=uploads/attachments/
attachments.storage.tasks-path=uploads/attachments/tasks/
attachments.storage.comments-path=uploads/attachments/comments/
attachments.storage.subtasks-path=uploads/attachments/subtasks/
jwt.secret=dGVzdGluZyB0aGUgYXBwIG5vdyB3aXRoIGJhc2UgNjQgZW5jb2RlZCBwYXNzd29yZCA=
spring.kafka.bootstrap-servers=192.168.1.2:9092
spring.kafka.producer.acks=all
app.kafka.topic.task-created=task-created
app.kafka.topic.task-updated=task-updated
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer


