spring:
  application:
    name: login-service

jwt:
  secret: ${JWT_SECRET}
  expirationMs: ${JWT_EXPIRATION}

grpc:
  port: 9093

management:
  endpoints:
    web.exposure.include: "*"
  endpoint:
    health.show-details: always
    info.enabled: true

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
