
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - ./data/zookeeper:/data
      - ./data/zookeeper/datalog:/datalog
    networks:
      - backendservices

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: /var/lib/kafka/data
    volumes:
      - ./data/kafka:/var/lib/kafka/data
    networks:
      - backendservices

  kafka-init:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka-init
    depends_on:
      - kafka
    volumes:
      - ./kafka/init-kafka.sh:/init-kafka.sh
    entrypoint: ["/bin/bash", "/init-kafka.sh"]
    networks:
      - backendservices

  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: kafdrop
    depends_on:
      - kafka
    ports:
      - "9001:9000"
    environment:
      KAFKA_BROKERCONNECT: PLAINTEXT://kafka:9092
    networks:
      - backendservices

  gateway-service:
    image: gateway-service:${IMAGE_VERSION}
    container_name: gateway-service
    build:
      context: ../
      dockerfile: gateway-service/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - login-service
      - task-service
      - notification-service
    volumes:
      - ./gateway-service/config/application.yml:/gateway/config/application.yml
      - ./gateway-service/config/application-${SPRING_PROFILES_ACTIVE}.yml:/gateway/config/application-${SPRING_PROFILES_ACTIVE}.yml
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SPRING_CONFIG_LOCATION=classpath:/,file:/gateway/config/
    networks:
      - backendservices

  login-service:
    image: login-service:${IMAGE_VERSION}
    container_name: login-service
    build:
      context: ../TaskManager
      dockerfile: login-service/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - kafka
      - postgres
    volumes:
      - ./login-service/config/application.yml:/login/config/application.yml
      - ./login-service/config/application-${SPRING_PROFILES_ACTIVE}.yml:/login/config/application-${SPRING_PROFILES_ACTIVE}.yml
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SPRING_CONFIG_LOCATION=classpath:/,file:/login/config/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${LOGIN_DB}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    networks:
      - backendservices

  task-service:
    image: task-service:${IMAGE_VERSION}
    container_name: task-service
    build:
      context: ../TaskManager
      dockerfile: task-service/Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - kafka
      - postgres
    volumes:
      - ./task-service/config/application.yml:/task/config/application.yml
      - ./task-service/config/application-${SPRING_PROFILES_ACTIVE}.yml:/task/config/application-${SPRING_PROFILES_ACTIVE}.yml
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SPRING_CONFIG_LOCATION=classpath:/,file:/task/config/
       - SPRING_DATASOURCE_URL=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${TASK_DB}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    networks:
      - backendservices
  notification-service:
    image: notification-service:${IMAGE_VERSION}
    container_name: notification-service
    build:
      context: ../notification-service
      dockerfile: Dockerfile
    depends_on:
      - kafka
      - login-service
    volumes:
      - ./notification-service/config.${SPRING_PROFILES_ACTIVE}.json:/notification/config.json
    networks:
      - backendservices

  appsmith:
    image: appsmith/appsmith-ce
    container_name: appsmith
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/appsmith:/appsmith-stacks
    networks:
      - backendservices

  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5433:5433"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backendservices


networks:
  backendservices:
    driver: bridge